services:
  - type: web
    name: sanin2025-osaka-poster
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: sanin2025-osaka-poster-db
    databaseName: poster_app
    user: poster_user
    plan: free 